steps:
  - name: 'node:14'
    args:
      - '-c'
      - npm install
    dir: angularapp
    entrypoint: bash
  - name: 'node:14'
    args:
      - '-c'
      - npm run build --prod
    dir: angularapp
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        us-central1-docker.pkg.dev/cloudcourseb9d41/frontend-images/angular-app:latest
      - .
    dir: angularapp
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        us-central1-docker.pkg.dev/cloudcourseb9d41/frontend-images/angular-app:latest
images:
  - >-
    us-central1-docker.pkg.dev/cloudcourseb9d41/frontend-images/angular-app:latest
options:
  logging: CLOUD_LOGGING_ONLY
