steps:
  - name: 'node:14'
    args:
      - install
    dir: /angularapp
    entrypoint: npm
  - name: 'node:14'
    args:
      - run
      - build
      - '--'
      - '--prod'
    dir: /angularapp
    entrypoint: npm
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        us-central1-docker.pkg.dev/cloudcourseb9d41/frontend-images/angular-app:latest
      - .
    dir: /angularapp
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        us-central1-docker.pkg.dev/cloudcourseb9d41/frontend-images/angular-app:latest
images:
  - >-
    us-central1-docker.pkg.dev/cloudcourseb9d41/frontend-images/angular-app:latest
